### ISSUE TITLE
Unable to load feed from an Odata Web API 2 controller

### ISSUE THREAD

**Issue by pnwnightowl** [OfficeDev/OData-Excel-Integration-Add-In-Sample#1]
If you change the ODataEndpointURL and ODataMetadataURL to point to a feed that is hosted via an Odata V4 or V3 Web API 2 controller, then you are unable to load any data.  The add-in simply displays "loading..."

**Comment by rapraj** [comment]
Have you added your own Authentication model on it?

**Comment by rapraj** [comment]
Jeff - can you let me know if you still see this issue?
