### ISSUE TITLE
Errors in Build

### ISSUE THREAD

**Issue by raikwar** [OfficeDev/OData-Excel-Integration-Add-In-Sample#11]
Hi 
I am using Visual Studio 2017.
I get the following errors during build.  

1>------ Rebuild All started: Project: ODSampleDataWeb, Configuration: Debug Any CPU ------
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\Animation.ts(1,8): error TS2300: Build:Duplicate identifier 'Animation'.
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\Animation.ts(330,45): error TS2702: Build:'Animation' only refers to a type, but is being used as a namespace here.
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\DataHelper.ts(54,39): error TS2559: Build:Type '(asyncResult: any) => void' has no properties in common with type '{ asyncContext?: any; }'.
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\DataHelper.ts(108,79): error TS2559: Build:Type '(asyncResult: any) => void' has no properties in common with type '{ valueFormat?: ValueFormat; filterType?: FilterType; asyncContext?: any; }'.
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\DataHelper.ts(194,42): error TS2559: Build:Type '(asyncResult: any) => void' has no properties in common with type '{ asyncContext?: any; }'.
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\DataHelper.ts(200,65): error TS2559: Build:Type '(asyncResult: any) => void' has no properties in common with type '{ asyncContext?: any; }'.
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\DataHelper.ts(207,13): error TS2559: Build:Type '(asyncResult: any) => void' has no properties in common with type '{ asyncContext?: any; }'.
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\DataHelper.ts(220,66): error TS2559: Build:Type '(asyncResult: any) => void' has no properties in common with type '{ asyncContext?: any; }'.
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\DataHelper.ts(240,65): error TS2559: Build:Type '(asyncResult: any) => void' has no properties in common with type '{ asyncContext?: any; }'.
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\DataHelper.ts(385,85): error TS2559: Build:Type '(asyncResult: any) => void' has no properties in common with type '{ coercionType?: CoercionType; asyncContext?: any; }'.
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\DataHelper.ts(388,92): error TS2559: Build:Type '(asyncResult: any) => void' has no properties in common with type '{ coercionType?: CoercionType; asyncContext?: any; }'.
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\DataHelper.ts(398,83): error TS2559: Build:Type '(asyncResult: any) => void' has no properties in common with type '{ coercionType?: CoercionType; asyncContext?: any; }'.
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\UX.BulgingDiffPage.ts(7,70): error TS2339: Build:Property 'getTargetBulgedDataIndex' does not exist on type 'RecordDiffList'.
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\UX.BulgingDiffPage.ts(15,49): error TS2339: Build:Property 'CosineCurveCalculator' does not exist on type '{ new (effect?: AnimationEffect, timeline?: AnimationTimeline): Animation; prototype: Animation; }'.
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\UX.BulgingDiffPage.ts(20,55): error TS2339: Build:Property 'getTargetBulgedDataIndex' does not exist on type 'RecordDiffList'.
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\UX.BulgingDiffPage.ts(26,55): error TS2339: Build:Property 'getTargetBulgedDataIndex' does not exist on type 'RecordDiffList'.
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\UX.BulgingDiffPage.ts(39,59): error TS2345: Build:Argument of type 'RecordDiffList' is not assignable to parameter of type 'IObserver'.
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\UX.BulgingDiffPage.ts(41,33): error TS2339: Build:Property 'sortElementsImmediately' does not exist on type 'RecordDiffList'.
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\UX.BulgingDiffPage.ts(42,33): error TS2339: Build:Property 'getBulgingAnimatingNumber' does not exist on type 'RecordDiffList'.
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\UX.BulgingDiffPage.ts(46,62): error TS2345: Build:Argument of type 'RecordDiffList' is not assignable to parameter of type 'IObserver'.
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\UX.BulgingDiffPage.ts(50,33): error TS2339: Build:Property 'bulgeData' does not exist on type 'RecordDiffList'.
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\UX.BulgingDiffPage.ts(54,40): error TS2339: Build:Property 'getDataObjects' does not exist on type 'RecordDiffList'.
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\UX.BulgingDiffPage.ts(58,44): error TS2339: Build:Property 'BulgingList' does not exist on type '{ new (effect?: AnimationEffect, timeline?: AnimationTimeline): Animation; prototype: Animation; }'.
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\UX.BulgingDiffPage.ts(59,38): error TS2702: Build:'Animation' only refers to a type, but is being used as a namespace here.
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\UX.BulgingDiffPage.ts(62,31): error TS2339: Build:Property 'JQueryAnimatingNumber' does not exist on type '{ new (effect?: AnimationEffect, timeline?: AnimationTimeline): Animation; prototype: Animation; }'.
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\UX.BulgingDiffPage.ts(67,18): error TS2339: Build:Property 'setFilter' does not exist on type 'RecordDiffList'.
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\UX.BulgingDiffPage.ts(71,31): error TS2339: Build:Property 'getDataObjects' does not exist on type 'RecordDiffList'.
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\UX.BulgingDiffPage.ts(71,53): error TS2339: Build:Property 'getTargetBulgedDataIndex' does not exist on type 'RecordDiffList'.
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\UX.BulgingDiffPage.ts(76,29): error TS2339: Build:Property 'getElementByData' does not exist on type 'RecordDiffList'.
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\UX.BulgingDiffPage.ts(81,22): error TS2339: Build:Property 'JQElement' does not exist on type 'RecordDiffList'.
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\UX.BulgingDiffPage.ts(81,53): error TS2339: Build:Property 'JQElement' does not exist on type 'RecordDiffList'.
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\UX.BulgingDiffPage.ts(85,60): error TS2339: Build:Property 'JQElement' does not exist on type 'RecordDiffList'.
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\UX.BulgingDiffPage.ts(87,26): error TS2339: Build:Property 'JQElement' does not exist on type 'RecordDiffList'.
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\UX.BulgingDiffPage.ts(87,66): error TS2339: Build:Property 'JQElement' does not exist on type 'RecordDiffList'.
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\UX.BulgingDiffPage.ts(97,36): error TS2339: Build:Property 'JQElement' does not exist on type 'RecordDiffList'.
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\UX.BulgingDiffPage.ts(171,65): error TS2339: Build:Property 'getBulgingAnimatingNumber' does not exist on type 'RecordDiffList'.
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\UX.BulgingDiffPage.ts(216,33): error TS2339: Build:Property 'getElementByData' does not exist on type 'RecordDiffList'.
1>C:\OData-Excel-Integration-Add-In-Sample-master\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\typings\Office\Office.d.ts(1480,9): error TS2416: Build:Property 'addHandlerAsync' in type 'ProjectDocument' is not assignable to the same property in base type 'Document'.
1>C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.1\lib.dom.d.ts(1704,11): error TS2300: Build:Duplicate identifier 'Animation'.
1>C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.1\lib.dom.d.ts(1729,13): error TS2300: Build:Duplicate identifier 'Animation'.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

Please let me know how to correct ?

**Comment by Rick-Kirkham** [comment]
Please close VS, then replace the ODSampleDataWeb.csproj with the new one here: [ODSampleDataWeb.csproj](https://github.com/OfficeDev/OData-Excel-Integration-Add-In-Sample/blob/master/Excel%20OData%20Connector/Excel%20OData%20Connector/ODSampleDataWeb/ODSampleDataWeb.csproj) 
Then try again and let us know if it worked.

**Comment by raikwar** [comment]
Thanks. It worked.
