### ISSUE TITLE
Setup instructions incorrect

### ISSUE THREAD

**Issue by jthake** [OfficeDev/OData-Excel-Integration-Add-In-Sample#2]
The current instructions do not work and there are issues in code that means it currently does not compile.

**Comment by rapraj** [comment]
Have updated the setup instructions. Do you have Excel 2016 in your system?

**Comment by jthake** [comment]
Thanks @rapraj , there is actually a bug in the code that doesn't compile. I did speak to the engineers when they came to my office in Redmond. I have Visual Studio 2015 and Office 2016 installed on my machine.

**Comment by rapraj** [comment]
@jthake - we're at it. we got it to work on our machines, just testing it out before we make the publish

**Comment by jthake** [comment]
Great. Look forward to it!

**Comment by rapraj** [comment]
We've updated the comments and instructions.
