### ISSUE TITLE
Build: Argument of type '{ cells: { row: number; column: number; }; format: { backgroundColor: string; }; }' is not assignable to parameter of type

### ISSUE THREAD

**Issue by jthake** [OfficeDev/OData-Excel-Integration-Add-In-Sample#3]
There is an error on compilation still, which I reported back in September directly to this team

`Severity   Code    Description Project File    Line    Suppression State
Error       Build: Argument of type '{ cells: { row: number; column: number; }; format: { backgroundColor: string; }; }' is not assignable to parameter of type '{ cells: { row: number; }; format: { backgroundColor: string; }; }'.   ODSampleDataWeb C:\Users\jthake\git\Odata-Excel-Integration-add-in-sample-fork\Excel OData Connector\Excel OData Connector\ODSampleDataWeb\Scripts\App\Record.ts    157`

I'm using Visual Studio 2015 Update 1 and TypeScript 1.7.6.0. I believe the line is incorrect.

**Comment by jthake** [comment]
I tried fixing the line to

`format.push({ cells: { row: rowId }, format: { backgroundColor: cell.UsingODataValue ? "#9dcbeb" : "#c6efce" } });`

But now when I F5 the project I get this error on load in Excel 2016. I'm guessing this isn't expected...

<img width="964" alt="err" src="https://cloud.githubusercontent.com/assets/6786616/12620405/04ba99d4-c4d1-11e5-88a5-c57ccf184972.png">

**Comment by rapraj** [comment]
Sorry it took us so long to respond. We will try to verify/reproduce that issue and respond here very soon.

**Comment by Rick-Kirkham** [comment]
I am not able to reproduce. If this is still an issue, please provide exact steps to reproduce.
