### ISSUE TITLE
Add-in no longer opens correctly

### ISSUE THREAD

**Issue by smich73** [OfficeDev/OData-Excel-Integration-Add-In-Sample#6]
This was working until a couple of months ago. Now, when I run the add-in for Excel desktop, the add-in appears and then auto closes/disappears.

**Comment by rapraj** [comment]
Sorry it took us so long to respond. We will try to verify/reproduce that issue and respond here very soon

**Comment by Rick-Kirkham** [comment]
I am not able to reproduce. If you are still having problems, can you provide exact repro steps?
