### ISSUE TITLE
Add-in Commands

### ISSUE THREAD

**Issue by webartoli** [OfficeDev/OData-Excel-Integration-Add-In-Sample#7]
Watching the video in [Add-in Commands in Office Ribbon @ Channel 9](https://channel9.msdn.com/Events/Visual-Studio/Connect-event-2015/316?ocid=player) i was expecting addin commands on the ribbon.

**Comment by rapraj** [comment]
Sorry it took us so long to respond. As I understand it you have a technical question about Add-in Commands. Please ask your question on stackoverflow.com. Tag your question 'office-js'
