### ISSUE TITLE
Doesn't support inserting new rows?

### ISSUE THREAD

**Issue by ghost** [OfficeDev/OData-Excel-Integration-Add-In-Sample#8]
I gave this a try but for now it seems to support deleting and updating but doesn't seems to handle newly added rows. Or do I miss something ?

**Comment by Rick-Kirkham** [comment]
I consulted with the product team. They tell me that the sample is not intended to support newly added rows. It is meant to show the basics of Excel-OData integration, not to include all functionality that a production add-in would likely have. If you think it would be valuable to the community to have a sample with this feature, you could either enhance the sample yourself and make a pull request, or go to [Office Dev User Voice](https://officespdev.uservoice.com/) and request a new or enhanced sample.
